# Generated by Django 2.0 on 2017-12-08 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=141)),
                ('authored', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owned_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=64, null=True)),
                ('purchased_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=5)),
                ('full_name', models.CharField(blank=True, max_length=64)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='estimated_net',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='stocks.Owned_Stock'),
        ),
        migrations.AddField(
            model_name='owned_stock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='owned_stock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
    ]
